# Netlify Configuration File

[[redirects]]
  from = "/"
  to = "/personal.html"
  status = 200

[[redirects]]
  from = "/guanglish"
  to = "/guanglish.html"
  status = 200

[[redirects]]
  from = "/340833165117"
  to = "/99.html"
  status = 200

[[redirects]]
  from = "/guanglish/*"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
